---
title: "Train_Test"
author: "Hassan Dahir"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
####-------------------------------####
source('../fun_0_loadLibrary.R')
####-------------------------------####
source('fun_2_2_trainRF.R')
source('fun_2_3_apply_optimalRF_avg.R')
```





```{r}
library(vroom)  
library(purrr)
library(partykit)
library(randomForest)
library(rpart.plot)
library(ranger)


```



```{r}
process_station <- function(apply_optimalRF, trainRF, train_data, columns_set_up, key, trees, mtry) {
  rf_input <- train_data %>% 
    dplyr::select(all_of(columns_set_up)) %>% 
    dplyr::mutate_all(as.numeric)
  
  optimal_ranger <- trainRF(input_table=rf_input, num.trees=trees, mtry=mtry)
  

  #save trained model and variable importance rank
  vi_df <- data.frame(names=names(optimal_ranger$variable.importance)) %>%
    mutate(importance=optimal_ranger$variable.importance)                     
  write.csv(vi_df, paste0(outputDir,'varImportance_', key, '.csv'), row.names=F)
  
  #run validation script
  KGE_list <- mclapply(1:nrow(testStationInfo), key=key, columns_set_up=columns_set_up, optimal_ranger=optimal_ranger, apply_optimalRF, mc.cores=1)
  #KGE_list <- mclapply(1:nrow(testStationInfo), key=key, columns_set_up, apply_optimalRF, mc.cores=1)
  rf.eval <- do.call(rbind,KGE_list)
  write.csv(rf.eval, paste0(outputDirValidation, 'KGE_' , key, '.csv'), row.names = F)
  
  # Save RF tree as a visual figure

}

```


```{r}
#-------train RF with tuned parameters on 70% of available observations----------
num.threads <- 48
num.cores <- 48
min.node.size = 5

#Keep one hyper parameters
trees <- 300

# Choose setup
data_sampling <- "rhine_only" 

for(subsample in 1:5){
    
    print(paste0('subsample: ', subsample))
    #select subsample predictors
    train_data <- vroom(paste0('../data/', data_sampling, '/subsample_', subsample,
                               '/train_table_allpredictors.csv'), show_col_type=F)
    
    # To validate the model, i use elbe and rhine as testing and for training i apply cross-valudation using rhine stations
    testStationInfo <- read.csv(paste0('../data/', data_sampling, '/subsample_',subsample,
      '/test_stations.csv')) #change the test_stations to validation_stations or the other way around
    
    outputDir <- paste0('../RF_output/train/', data_sampling, '/subsample_',subsample,'/')
    dir.create(outputDir, showWarnings = F, recursive = T)
      
    outputDirValidation <- paste0('../RF_output/validate/', data_sampling, '/subsample_',subsample,'/')
    dir.create(outputDirValidation, showWarnings = F, recursive = T)
  

  # Rename the column "Obs_dis" to "obs"
  colnames(train_data)[colnames(train_data) == "pcr_dis"] <- "pcr"
  colnames(train_data)[colnames(train_data) == "lis_dis"] <- "lis"
  colnames(train_data)[colnames(train_data) == "wg3_dis"] <- "wg3"

  print(colnames(train_data))
  ### Discharge only ### 

  
  #print('training: pcr discharge only')
  columns_set_up_4.1 <- c("pcr", "lis", "wg3", "obs")
  columns_set_up_4.2 <-  c("meteo_rain", "meteo_tair", "pcr", "lis", "wg3", "obs")
  columns_set_up_4.3 <-  c("meteo_rain", "meteo_tair", "wg3", "wg3_RootMoist", "wg3_SurfStor", "wg3_SWE",
                  "lis", "lis_SurfMoist", "lis_SWE", "pcr", "pcr_SurfMoist", "pcr_SurfStor",
                  "pcr_SWE", "obs")
  
  
  #### Input data when all models are combined   #### 
  
  rf_input4.1 <- 
    train_data %>% 
    select(all_of(columns_set_up_4.1))  %>% 
    mutate_all(as.numeric)  %>% 
    mutate(across(c("pcr", "lis", "wg3"), as.numeric))
  
  rf_input4.2 <- 
    train_data %>% 
    select(all_of(columns_set_up_4.2))  %>% 
    mutate_all(as.numeric)  %>% 
    mutate(across(c("pcr", "lis", "wg3"), as.numeric)) 
  
  rf_input4.3 <- 
    train_data %>% 
    select(all_of(columns_set_up_4.3))  %>% 
    mutate_all(as.numeric) %>% 
    mutate(across(c("pcr", "lis", "wg3"), as.numeric))
  

  #process_station(apply_optimalRF, trainRF, rf_input4.1, columns_set_up_4.1, "all_dis", trees, 1)
  
  #print('training: pcr discharge and meteo')
  
  #process_station(apply_optimalRF, trainRF, rf_input4.2, columns_set_up_4.2, "all_dis_meteo", trees, 3)
  
  #print('training: all pcr predictors and meteo')
  process_station(apply_optimalRF, trainRF, rf_input4.3, columns_set_up_4.3, "allpredictors", trees, 4)
  

}
```
