---
title: "Tuning RF"
author: "Hassan Dahir"
date: "2023-06-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
####-------------------------------####
source('../fun_0_loadLibrary.R')
```

```{r}
####-------------------------------####
source('fun_2_1_hyperTuning.R')
```



```{r}
#--------------RF---------------
#-----------1. Tune parameter---------------#
num.threads <- 48 
min.node.size = 5

columns_set_up_1 <-  c("meteo_rain", "meteo_tair", "wg3", "wg3_RootMoist", "wg3_SurfStor", "wg3_SWE",
                "lis", "lis_SurfMoist", "lis_SWE", "pcr", "pcr_SurfMoist", "pcr_SurfStor",
                "pcr_SWE", "obs")
columns_set_up_2<-  c("meteo_rain", "meteo_tair", "pcr", "lis", "wg3", "obs")


data_sampling <- "pcr_rhine"

for(subsample in 1:5){

  print(paste0('subsample: ', subsample))
  #select subsample predictors
  
  train_data <- vroom(paste0('../data/', data_sampling, '/subsample_', subsample,
                             '/train_table_allpredictors.csv'), show_col_type=F)
  
  colnames(train_data)[colnames(train_data) == "pcr_dis"] <- "pcr"
  colnames(train_data)[colnames(train_data) == "lis_dis"] <- "lis"
  colnames(train_data)[colnames(train_data) == "wg3_dis"] <- "wg3"
  
  
  outputDir <- paste0('../RF_output/tune/', data_sampling, '/subsample_',subsample,'/')
  dir.create(outputDir, showWarnings = F, recursive = T)
  
  #tuning
  #### all predictors ####
  print('tuning: allpredictors')
  
  rf_input_allpredictors <- 
    train_data %>% 
    select(all_of(columns_set_up_1))  %>% 
    mutate_all(as.numeric)
    
  
  hyper_grid <- expand.grid(
    ntrees = c(100,150,200,300,500, 600, 700, 800), 
  #~       ntrees = 200, #only use 200 trees for rapid tuning
  #~       mtry = seq(11,21, by=1)
    mtry = 4 #seq(2, 8, by=1)  #4 # Based on tunning on #seq(2, 8, by=1) and ntrees = 200
  )
  
  hyper_trains <- lapply(1:nrow(hyper_grid), rf_input=rf_input_allpredictors, hyper_tuning)
  
  for(i in 1:nrow(hyper_grid)){
    hyper_grid$ntrees[i]   <- hyper_trains[[i]]$num.trees
    hyper_grid$mtry[i]     <- hyper_trains[[i]]$mtry
    hyper_grid$OOB_RMSE[i] <- sqrt(hyper_trains[[i]]$prediction.error)
  }
    
  print(paste0('output csv file: ', outputDir, 'hyper_grid_allpredictors_ntrees.csv'))
  write.csv(hyper_grid, paste0(outputDir, 'hyper_grid_allpredictors_ntrees.csv'), row.names = F)
  
  
  #### qmeteostatevars ####
  print('tuning: qMeteoStatevars')
  
  
  rf_input_meteo <- 
    train_data %>% 
    select(all_of(columns_set_up_2))  %>% 
    mutate_all(as.numeric)
    
    
  
  hyper_grid <- expand.grid(
    ntrees = c(100,150,200,300,500, 600, 700, 800), 

    mtry = 3 #seq(2, 4, by=1) #3 # Based on tunning on seq(2, 4, by=1) and ntrees = 200
  )
  
  hyper_trains <- lapply(1:nrow(hyper_grid), rf_input=rf_input_meteo, hyper_tuning)
  
  for(i in 1:nrow(hyper_grid)){
    hyper_grid$ntrees[i]   <- hyper_trains[[i]]$num.trees
    hyper_grid$mtry[i]     <- hyper_trains[[i]]$mtry
    hyper_grid$OOB_RMSE[i] <- sqrt(hyper_trains[[i]]$prediction.error)
  }
    
  print(paste0('output csv file: ', outputDir, 'hyper_grid_qMeteoStatevars_ntrees.csv'))
  write.csv(hyper_grid, paste0(outputDir, 'hyper_grid_qMeteoStatevars_ntrees.csv'), row.names = F) #_ntrees
    
}

```






