---
title: "VarImportance"
author: "Hassan Dahir"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
####-------------------------------####
source('../fun_0_loadLibrary.R')
####-------------------------------####
```


```{r}
sc <- scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#CC79A7"), 
                         name='Subsample: ')



#setup <- c("pcr_dis", "pcr_dis_meteo", "pcr_allpredictors")
setup <- c('all_dis','all_dis_meteo', "allpredictors")


remove <- c("Unnamed..0", 'datetime', 'obs')
predNames <- read.csv('../data/allpredictors/allpredictors_6335060.csv') %>% 
  names(.) %>% setdiff(.,remove) 

data_setup <- "all_stations"
outputDir <- paste0('../viz/', data_setup, '/')

dir.create(outputDir, showWarnings = F, recursive = T)
```




```{r}
predNames <- sub("(dis)\\b", "FlowDepth", predNames)
```


```{r}
predNames
```



```{r}
#### 5 subsamples variable importance ####
viList <- list()
viPlotList <- list()

meteoPred_names <- predNames[1:2]
wg3Pred_names <- predNames[3:6]
lisPred_names <- predNames[7:9]
pcrPred_names <- predNames[10:13]

colorPalette <- c(pcr = "red", lis = "blue", wg3 = "green", meteo = "orange")

for(i in 1:3){
  
  for(subsample in 1:5){
    
    trainDir <- paste0('../RF_output/train/all_stations', '/subsample_',subsample,'/')
    
    if(subsample==1){
      viList[[subsample]] <- read.csv(paste0(trainDir, 'varImportance_',setup[i],'.csv')) %>% 
        rename(importance_1=importance)
    } else{
      viList[[subsample]] <- read.csv(paste0(trainDir, 'varImportance_',setup[i],'.csv')) %>%
        select(., importance) %>%  rename(!!paste0('importance_',subsample) := importance)
    }
  }
  
  
  viSetup <- as.data.frame(do.call(cbind, viList))
  

  
  # calculate avg and standard deviation of variable importances
  for(j in 1:nrow(viSetup)){
    viSetup$importance_avg[j] <- sum(viSetup[j,2:6])/5
    viSetup$importance_sd[j] <- sd(viSetup[j,2:6])
  }
  
  
  viSetup$names <- gsub("\\b(pcr|wg3|lis)\\b", "\\1_FlowDepth", viSetup$names)

  

  #gather
  plotData <- viSetup %>% top_n(20, importance_avg) %>% 
    select(-(importance_1:importance_5)) %>% 
    arrange(., desc(importance_avg)) %>%
    gather('key','value', importance_avg) 
  
  # add predictor type (static or time-variant) to color plot text
  for(j in 1:nrow(plotData)){
    plotData$predictorType[j] <- case_when((plotData$names[j] %in% pcrPred_names)~'pcr',
                                           (plotData$names[j] %in% lisPred_names)~'lis',
                                           (plotData$names[j] %in% wg3Pred_names)~'wg3',
                                          (plotData$names[j] %in% meteoPred_names)~'meteo')
    #Assign color based on predictor type
    
    plotData$labColor[j] <- colorPalette[plotData$predictorType[j]]
    
  }
  

   # plot
  viPlot <- ggplot(plotData) +
    geom_col(
      aes(reorder(names, c(value[key == 'importance_avg'])), sqrt(value)),
      position = 'dodge', fill = plotData$labColor
    ) +
    geom_errorbar(
      aes(
        reorder(names, c(value[key == 'importance_avg'])),
        ymin = sqrt(value) - sqrt(importance_sd),
        ymax = sqrt(value) + sqrt(importance_sd),
        width = 0.8, size = 0.1, colour = "black"
      ),
      show.legend = FALSE
    ) +
    ylim(0, 0.10) +
    coord_flip() +
    theme_light() +
    labs(x = NULL, y = NULL,  title = paste0('\n', setup[i], '\n')) + #x = NULL, y = '\nSquare Root of Node Impurity Measure', 
    theme(
      axis.text.y = element_text(size = 35, color = "black"),
      axis.text.x = element_text(size = 33),
      title = element_text(size = 40)
    )
  
  viPlotList[[i]] <- viPlot

}

# Arrange the plots in a grid layout
gridPlot <- grid.arrange(grobs = viPlotList, nrow = 3, ncol = 1)

ggsave(paste0(outputDir, 'varImportance_all.png'), gridPlot, height=30, width=25, units='in', dpi=600)

```


```{r}
else {
    viPlot <- ggplot(plotData) +
      geom_col(
        aes(reorder(names, c(value[key == 'importance_avg'])), sqrt(value)),
        position = 'dodge', fill = plotData$labColor
      ) +
      geom_errorbar(
        aes(
          reorder(names, c(value[key == 'importance_avg'])),
          ymin = sqrt(value) - sqrt(importance_sd),
          ymax = sqrt(value) + sqrt(importance_sd),
          width = 0.8, size = 0.1, colour = "black"
        ),
        show.legend = FALSE
      ) +
      ylim(0, 0.65) +
      coord_flip() +
      theme_light() +
      labs(x = NULL, y = NULL, title = paste0('\n', setup[i], '\n')) +
      theme(
        axis.text.y = element_text(size = 35, color = "black"),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        title = element_text(size = 40)
      )
  }
  
  viPlotList[[i]] <- viPlot
```








```{r}
trainingPlot <- viPlotList[[1]] / viPlotList[[2]] / viPlotList[[3]]  
trainingPlotSize <- trainingPlot #+ plot_layout(heights=c(5,3,3))
trainingPlotSize

ggsave(paste0(outputDir, 'varImportance.png'), trainingPlotSize, height=8, width=10, units='in', dpi=600)


```


```{r}
# add predictor type (static or time-variant) to color plot text

plotData
```