---
title: "3_viz_KGE_boxplots"
author: "Hassan Dahir"
date: "2023-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
####-------------------------------####
source('../fun_0_loadLibrary.R')
####-------------------------------####
```


```{r}
library('ggh4x')
```



```{r}
library(ggplot2)
```


```{r}
# cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")  #with grey
# cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7") #with black
data_sampling <- "rhine_only"
model <- "MLR"

outputDir <- paste0('../viz/', data_sampling, "/")
if (!dir.exists(outputDir)) {
  dir.create(outputDir, showWarnings = FALSE, recursive = TRUE)
}

#setup <- c("uncalibrated", 'all_dis','all_dis_meteo', "allpredictors")

setup <- c("average", "pcr_dis", "lis_dis", "wg3_dis", 'all_dis','all_dis_meteo', "allpredictors")

output_folder <- paste0("../", model,"_output/") #RF_output
```



```{r}
#### data preparation ####
  subsample_KGE_list <- list ()



for(subsample in 1:5){
  
  
  rf.eval.mean <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                          '/KGE_allpredictors.csv')) %>%
    select(.,grdc_no, KGE, KGE_r, KGE_alpha, KGE_beta) %>%
    mutate(.,setup=factor(setup[1])) %>% 
    mutate(.,subsample=factor(subsample))
  
  
  
  #PCR discharge
  rf.eval.pcr.uncalibrated <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                          '/KGE_allpredictors.csv')) %>%
    select(.,grdc_no, KGE_pcr, KGE_r_pcr, KGE_alpha_pcr, KGE_beta_pcr) %>% 
    rename(., KGE=KGE_pcr, KGE_r=KGE_r_pcr, KGE_alpha=KGE_alpha_pcr, KGE_beta=KGE_beta_pcr) %>% 
    mutate(.,setup=factor(setup[2])) %>% 
    mutate(.,subsample=factor(subsample))
  
  rf.eval.lis.uncalibrated <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                                '/KGE_allpredictors.csv')) %>%
    select(., grdc_no, KGE_lis, KGE_r_lis, KGE_alpha_lis, KGE_beta_lis) %>% 
    rename(., KGE = KGE_lis, KGE_r = KGE_r_lis, KGE_alpha = KGE_alpha_lis, KGE_beta = KGE_beta_lis) %>% 
    mutate(., setup = factor(setup[3])) %>% 
    mutate(., subsample = factor(subsample))
    
  
  rf.eval.wg3.uncalibrated <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                              '/KGE_allpredictors.csv')) %>%
    select(., grdc_no, KGE_wg3, KGE_r_wg3, KGE_alpha_wg3, KGE_beta_wg3) %>% 
    rename(., KGE = KGE_wg3, KGE_r = KGE_r_wg3, KGE_alpha = KGE_alpha_wg3, KGE_beta = KGE_beta_wg3) %>% 
    mutate(., setup = factor(setup[4])) %>% 
    mutate(., subsample = factor(subsample))
  
  
  #read all_dis of different models
  rf.eval.all_dis <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                           '/KGE_all_dis.csv')) %>% 
    select(.,grdc_no, KGE_corrected, KGE_r_corrected, KGE_alpha_corrected, KGE_beta_corrected) %>% 
    rename(., KGE=KGE_corrected, KGE_r=KGE_r_corrected, KGE_alpha=KGE_alpha_corrected, KGE_beta=KGE_beta_corrected) %>% 
    mutate(.,setup=factor(setup[5])) %>% 
    mutate(.,subsample=factor(subsample)) 

  
  #read pcr + meteo
  rf.eval.all.dis.meteo <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                           '/KGE_all_dis_meteo.csv')) %>% 
    select(.,grdc_no, KGE_corrected, KGE_r_corrected, KGE_alpha_corrected, KGE_beta_corrected) %>% 
    rename(., KGE=KGE_corrected, KGE_r=KGE_r_corrected, KGE_alpha=KGE_alpha_corrected, KGE_beta=KGE_beta_corrected) %>% 
    mutate(.,setup=factor(setup[6])) %>% 
    mutate(.,subsample=factor(subsample)) 
  
  
  #read pcr + meteo  + pcr statevariables
  rf.eval.allpredictors <- read.csv(paste0(output_folder, 'validate/',data_sampling, '/subsample_',subsample,
                                           '/KGE_allpredictors.csv')) %>% 
    select(.,grdc_no, KGE_corrected, KGE_r_corrected, KGE_alpha_corrected, KGE_beta_corrected) %>% 
    rename(., KGE=KGE_corrected, KGE_r=KGE_r_corrected, KGE_alpha=KGE_alpha_corrected, KGE_beta=KGE_beta_corrected) %>% 
    mutate(.,setup=factor(setup[7])) %>% 
    mutate(.,subsample=factor(subsample))
  

  
  #put together in one list
  subsample_KGE <- rbind(rf.eval.mean, rf.eval.pcr.uncalibrated, rf.eval.lis.uncalibrated, rf.eval.wg3.uncalibrated, 
                         rf.eval.all_dis, rf.eval.all.dis.meteo, rf.eval.allpredictors)
  subsample_KGE_list[[subsample]] <- subsample_KGE
 
  
}

```



```{r}
allData <- do.call(rbind, subsample_KGE_list)
allDataCum <- allData %>% mutate(subsample='Cumulative')
allData <- rbind(allData,allDataCum)


plotData <- allData %>% 
  pivot_longer(KGE:KGE_beta, names_to = "KGE_component", 
                                     values_to = "value") %>% 
  mutate(setup = factor(setup, levels=  c("average", "pcr_dis", "lis_dis", "wg3_dis", 'all_dis','all_dis_meteo', "allpredictors"))) %>%
  mutate(KGE_component = fct_relevel(KGE_component, 'KGE','KGE_r','KGE_alpha','KGE_beta'))
```


```{r}
allData
```



```{r}
KGE_data <-
  plotData %>% 
  filter(., KGE_component == "KGE") %>% 
  group_by(subsample, setup) %>%
  filter(., subsample=="Cumulative") %>% 

  summarize(median_value = median(value)) %>% 
  pivot_wider(names_from = subsample, values_from = median_value)

KGE_data
```


```{r}
filename <- paste0('median_KGE_', model, '.csv')

# Save the data frame as a CSV file
write.csv(KGE_data, file = paste0(outputDir, filename), row.names = FALSE)
```




```{r}
#### plot boxplots ####
KGE_boxplot <- 
  plotData %>% 
  filter(., subsample=="Cumulative") %>% 

  filter(., KGE_component %in% c("KGE")) %>% #, "KGE_r", "KGE_alpha", "KGE_beta"
  ggplot(. , mapping = aes(setup, value, fill=setup))+
  geom_boxplot(outlier.shape = NA) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  facet_grid(vars(KGE_component), vars(subsample), scales='free_y', switch='y')+
  labs(title = paste0("Subsampling ", data_sampling, " ", model))+
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F8766D", "#00BFC4", "#7CAE00"))+
  theme(plot.title = element_text(hjust=0.5, size=16),
        axis.title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y= element_text(size=12),
        legend.position = 'bottom',
        legend.title=element_blank(),
        legend.key.size = unit(1, 'cm'),
        legend.text = element_text(size=14),
        strip.text = element_text(size=12))+
  facetted_pos_scales(y = list(
    KGE_component == "KGE" ~ scale_y_continuous(position='right', limits = c(-1, 1))))
    #KGE_component == "KGE_r" ~ scale_y_continuous(position='right', limits = c(0, 1)),
    #KGE_component == "KGE_alpha" ~ scale_y_continuous(position='right', limits = c(-0.5,5)),
    #KGE_component == "KGE_beta" ~ scale_y_continuous(position='right', limits = c(-0.5,5.5))))
KGE_boxplot
```




```{r}
ggsave(paste0(outputDir,'KGE_boxplot_', data_sampling, model, '.png'), KGE_boxplot, height=8, width=8, units='in', dpi=600)

```




```{r}


# Create a scatter plot of residuals against predicted values
ggplot(mlr_result, aes(x = dis_corrected, y = res_corrected)) +
  geom_point() +
  xlab("Predicted values") +
  ylab("Residuals") +
  ggtitle("Residuals vs. Predicted Values") +
  theme_minimal()

# Save the plot to a file
plot_file <- paste0(outputDirTables, 'residuals_plot_', station_no, '.png')
ggsave(plot_file

```

















